@startuml logical formula
package fol {
class Lobject {
    + {abstract} parse(cls, Ldict)
    + {abstract} Ldict to_ldict(self)
    + {abstract} lstr to_lstr(self)
    + {abstract} Dict[Str, Term] get_terms(self)
    + __repr__()
}

note right
    connects Lobject and Ldict,
    which represents all first order objects.
    Ldict contains all the information about a sample,
    even though the samples information can be empty
end note

' TODO
class Term {
    + {static} int EXISTENTIAL
    + {static} int FREE
    + {static} int UNIVERSAL
    + {static} int LITERAL
    + {static} int op

    + int state
    + str name
    + int batch_size
    + list entity_id_list
    + Tensor batch_embedding
    + List[Tensor] batch_proposal_list

    + parse(cls, Ldict Ldict)
    + Ldict to_ldict(self)
    + Dict[Str, Term] get_terms(self)

    + void append_proposals(self, Tensor batch_proposition)
    + void update_embedding_by_proposals(self)
    + void update_entity_id_by_embedding(self, NeuralBinaryPredicate nbp)
    + void update_embedding_by_entity_id(self, NeuralBinaryPredicate nbp)
}

Lobject <|-- Term

class Formula {
    + {abstract} Dict[Str,Term] get_terms(self)
    + {abstract} Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + {abstract} Tensor get_truth_value(self)
}

Lobject <|-- Formula
Formula <|-- BinaryPredicate

class BinaryPredicate {
    + {static} op
    + name
    + relation_id_list
    + term1
    + term2

    + parse(cls, Ldict)
    + to_ldict(self)
    + Dict[Str,Term] get_terms(self)
    + Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + Tensor get_truth_value(self)
}

BinaryPredicate *-- Term : contains two Terms

class Negation {
    + {static} op
    + formula
    + parse(cls, Ldict)
    + to_ldict(self)
    + Dict[Str,Term] get_terms(self)
    + Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + Tensor get_truth_value(self)
}

Formula <|-- Negation
Negation *-- Formula

class Conjunction {
    + {static} op
    + formulas
    + parse(cls, Ldict)
    + to_ldict(self)
    + Dict[Str,Term] get_terms(self)
    + Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + Tensor get_truth_value(self)
}

Formula <|-- Conjunction
Conjunction o-- Formula

class Disjunction {
    + {static} op
    + formulas
    + parse(cls, Ldict)
    + to_ldict(self)
    + Dict[Str,Term] get_terms(self)
    + Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + Tensor get_truth_value(self)
}

Formula <|-- Disjunction
Disjunction o-- Formula

class FirstOrderFormula {
    + Dict fvars_dict
    + Dict evars_dict
    + Dict uvars_dict
    + Dict predicate_dict
    + Formula formula
    + List[int] observed_answers
    + List[int] hard_answers
    + Dict[Str,Term] get_terms(self)
    + Dict[Str,NeuralBinaryPredicate] get_predicates(self)
    + Tensor get_truth_value(self)
    + bool is_query(self)
    + bool is_sentence(self)
}

FirstOrderFormula *-- Formula
FirstOrderFormula *-- BinaryPredicate
FirstOrderFormula *-- Term
}
@enduml