cuda: 0

knowledge_graph: 
  # TODO: generated graph in the uniform format
  filelist:
    - datasets-knowledge-embedding/FB15K/edges_as_id_train.tsv

neural_binary_predicate:
  name: transe
  params:
    embedding_dim: 600

trainer:
  objective: pairwise          # nce or pairwise
  margin: 20              # used in both nce and pairwise objective
  k_nce: 1                # 1 for pairwise
  num_neg_samples: 1      # 1 for pairwise
  ns_strategy: lcwa       # lcwa or lcwa+rel
  batch_size: 128
  num_steps: 10000

optimizer:
  name: Adam
  params:
    lr: 0.01

learner: 
  name: I
  params:
    efg_round: 5
    # TODO: greedy implementation
    efg_mode: random  # random or greedy
    efg_rand_thr: 0.5 # only worked when random 
                          # 0 for totally finite, 1 for totally neural
    neural_act_search_size: 10

evaluation:
  eval_every: 500
  # implement the task interface
  task_dict: 
    valid: 
      name: LinkPrediction
      params: 
        filelist: 
          - datasets-knowledge-embedding/FB15K/edges_as_id_valid.tsv
    test:
      name: LinkPrediction
      params: 
        filelist: 
          - datasets-knowledge-embedding/FB15K/edges_as_id_test.tsv

logdir: log/default
