cuda: 0

knowledge_graph:
  filelist:
    - data/FB15K/train_kg.tsv
  kgindex_file: data/FB15K/kgindex.json

neural_binary_predicate:
  name: swtranse
  params:
    embedding_dim: 30
    num_particles: 10
    margin: 1
    scale: 1
    p: 1

trainer:
  objective: pairwise          # nce or pairwise
  margin: 1                    # used in both nce and pairwise objective
  k_nce: 1                     # 1 for pairwise
  num_neg_samples: 1           # 1 for pairwise
  ns_strategy: lcwa            # lcwa or lcwa+rel
  batch_size: 100
  num_steps: -1
  num_epochs: 1000

optimizer:
  name: Adam
  params:
    lr: 0.01

learner:
  name: I
  params:
    efg_round: 5
    efg_mode: random  # random or greedy
    efg_rand_thr: 0.5 # only worked when random
                          # 0 for totally finite, 1 for totally neural
    neural_act_search_size: 10

dev_evaluation:
  eval_every_step: -1
  eval_every_epoch: 50
  observed_triple_filelist:
    - data/FB15K/train_kg.tsv
  kgindex_file: data/FB15K/kgindex.json
  task_dict:
    dev:
      name: LinkPrediction
      params:
        filelist:
          - data/FB15K/valid_kg.tsv
  dev_key: filter/agg/mrr

test_evaluation:
  eval_every_step: -1
  eval_every_epoch: 50
  observed_triple_filelist:
    - data/FB15K/train_kg.tsv
  kgindex_file: data/FB15K/kgindex.json
  task_dict:
    test:
      name: LinkPrediction
      params:
        filelist:
          - data/FB15K/test_kg.tsv

logdir: log/FB15K/swtranse_30_10n
