"""
A base class for existential first order formulas
It supports the verification and query answering tasks given the formula
For the verification, there is no free_vars
For the query answering, there should be at least one free_vars
Several assumptions about the formula
- In DNF
- Only with existential quantifier
The query is generated by the following steps:

>>>> Construct the conjunctive query skeleton:
    1. Define the number of terms, including
        - p existential vars
        - q free vars
        - r literals
        There are p + q + r terms
    2. Construct the edges between terms by random sampling, and then construct
        a connective graph, the edge is constructed by the certain ratio $P_e$
    3. Randomly corrupt the edges with negation $P_n$
<<<< In this way, the conjunctive query skeleton is constructed

>>>> Construct the DNF formula
    The key of DNF construction is that there must be at least one variable be
    shared in two conjunctive query
    1. determin the variables to be shared (more than one)
    2. determin the objects to be shared (not necessary more than one)
<<<<

>>>> Sampling accross the graph
    1. For question answering task
        1. sample the full graph,
            so that the predicates and objects are determined
        2. search over partial graph and full graph,
            and find out the answer tuples
    2. Instantiation of the query graph
<<<<
"""

from abc import abstractmethod
import json
from typing import Dict, List
from random import sample

import torch

from src.language.tnorm import ProductTNorm, Tnorm
from src.structure.neural_binary_predicate import NeuralBinaryPredicate


def check_ldict(ldict):
    """
    Ldict is a nested dict that stores the GROUNDED information
    """
    assert 'op' in ldict
    op = ldict['op']
    assert 'args' in ldict
    args = ldict['args']

    if op == Term.op:
        assert 'name' in args
        assert 'state' in args
        assert 'entity_id_list' in args
    if op == BinaryPredicate.op:
        assert 'name' in args
        assert 'relation_id_list' in args
        check_ldict(args['term1'])
        check_ldict(args['term2'])
    if op == Negation.op:
        assert 'formula' in args
        check_ldict(args['formula'])
    if op == Conjunction.op or op == Disjunction.op:
        assert 'formulas' in args
        for f in args['formulas']:
            check_ldict(f)


def get_ldict(op, **args):
    ans = {'op': op, 'args': args}
    check_ldict(ans)
    return ans


class Lobject:
    op = "default"

    @abstractmethod
    def to_ldict(self) -> Dict:
        pass

    @abstractmethod
    def lstr(self) -> str:
        pass

    def __repr__(self):
        check_ldict(self.to_ldict())
        return json.dumps(self.to_ldict(), indent=1)

    @abstractmethod
    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        pass


class Term(Lobject):
    EXISTENTIAL = 1
    FREE = 2
    UNIVERSAL = 3
    SYMBOL = 4
    GROUNDED = 5

    op = "term"

    def __init__(self, state, name):
        self.state = state
        self.name = name
        self.parent_predicate = None
        self.entity_id_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        name = args['name']
        state = args['state']
        object = cls(name=name, state=state)
        object.entity_id_list = args['entity_id_list']
        return object

    def to_ldict(self):
        ldict = {'op': self.op,
                 'args': {
                     'state': self.state,
                     'name': self.name,
                     'entity_id_list': self.entity_id_list}}
        return ldict

    def lstr(self) -> str:
        return self.name

    @property
    def is_free(self):
        return self.state == self.FREE

    @property
    def is_existential(self):
        return self.state == self.EXISTENTIAL

    @property
    def is_universal(self):
        return self.state == self.UNIVERSAL

    @property
    def is_symbol(self):
        return self.state == self.SYMBOL

    @property
    def is_grounded(self):
        return self.is_symbol or (self.state == Term.GROUNDED)


class Formula(Lobject):
    def __init__(self) -> None:
        super().__init__()

    @staticmethod
    def parse(ldict):
        op = ldict['op']
        if op == BinaryPredicate.op:
            return BinaryPredicate.parse(ldict)
        elif op == Negation.op:
            return Negation.parse(ldict)
        elif op == Conjunction.op:
            return Conjunction.parse(ldict)
        elif op == Disjunction.op:
            return Disjunction.parse(ldict)
        else:
            raise NotImplementedError("Unsupported Operator")


class BinaryPredicate(Formula):
    op = 'pred'

    def __init__(self,
                 name: str,
                 head: Term,
                 tail: Term) -> None:
        self.name = name
        self.head = head
        self.tail = tail
        self.relation_id_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']

        name = args['name']
        head = Term.parse(args['head'])
        tail = Term.parse(args['tail'])
        object = cls(name=name, head=head, tail=tail)
        object.relation_id_list = args['relation_id_list']
        head.parent_predicate = object
        tail.parent_predicate = object
        return object

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {
                'name': self.name,
                'relation_id_list': self.relation_id_list,
                'head': self.head.to_ldict(),
                'tail': self.tail.to_ldict()
            }
        }
        return obj

    def lstr(self):
        lstr = f"{self.name}({self.head.name},{self.tail.name})"
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {self.name: self}
        return ans

    def get_terms(self):
        return [self.head, self.tail]


class Connective(Formula):
    pass


class Negation(Connective):
    op = 'neg'

    def __init__(self, formula: Formula) -> None:
        self.formula = formula

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula = Formula.parse(args['formula'])
        return cls(formula)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formula': self.formula.to_ldict()}
        }
        return obj

    def lstr(self) -> str:
        lstr = f"!({self.formula.lstr()})"
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        ans.update(self.formula.get_predicates())
        return ans


class Conjunction(Connective):
    op = 'conj'

    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict)
                    for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def lstr(self):
        lstr = "&".join(f"({f.lstr()})" for f in self.formulas)
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


class Disjunction(Connective):
    op = 'disj'

    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict)
                    for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def lstr(self):
        lstr = "|".join(f"({f.lstr()})" for f in self.formulas)
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


def get_term_embed_from_formula(nbp: NeuralBinaryPredicate,
                                formula: "FirstOrderFormula",
                                term_name,
                                all_candidates=False):
    if all_candidates:
        if formula.term_dict[term_name].state == Term.FREE:
            return nbp.entity_embedding.unsqueeze(-2)

    if formula.has_term_grounded_entity_id_list(term_name):
        emb = nbp.get_entity_emb(
            formula.get_term_grounded_entity_id_list(term_name)
        )
    elif formula.has_var_local_embedding(term_name):
        emb = formula.get_var_local_embedding(term_name)
    else:
        raise KeyError("Embedding does not found")
    return emb



class FirstOrderFormula:
    """
    The first order formula
    it also includes information about the quantifiers

    self.formula is parsed from the formula and provide the operator tree for
        evaluation
    self.predicate_dict stores each predicates by its name, which are edges
    self.symbol_dict stores each symbol by its name
    self.variable_dict stores each variable by its name

    self.easy_answer_list list for easy answers
    self.hard_answer_list list for hard answers
    self.noisy_answer_list list for noisy answers

    each answer is a dict whose keys are the variable and values are the list of possible answers
    """

    def __init__(self,
                 formula: Formula) -> None:
        self.formula: Formula = formula
        self.easy_answer_list = []
        self.hard_answer_list = []
        self.noisy_answer_list = []

        # update internal storage
        self.predicate_dict: Dict[str, BinaryPredicate] = {}
        self.pred_grounded_relation_id_dict: Dict[str, List] = {}

        self.term_dict: Dict[str, Term] = {}
        self.term_local_embedding_dict: Dict[str, torch.Tensor] = {}
        self.term_grounded_entity_id_dict: Dict[str, List] = {}
        # run initialization
        self._init_query()

    def _init_query(self):
        self.predicate_dict = self.formula.get_predicates()
        self.pred_grounded_relation_id_dict = {
            name: predicate.relation_id_list
            for name, predicate in self.predicate_dict.items()
        }

        self.term_dict = {}
        for _, pred in self.predicate_dict.items():
            for t in pred.get_terms():
                self.term_dict[t.name] = t

        self.term_local_embedding_dict = {name: None
                                          for name in self.term_dict}
        self.term_grounded_entity_id_dict = {name: term.entity_id_list
                                        for name, term in self.term_dict.items()}

    def append_relation_and_symbols(self, append_dict):
        for k, v in append_dict.items():
            if k in self.term_dict:
                self.term_grounded_entity_id_dict[k].append(v)
            else:
                self.pred_grounded_relation_id_dict[k].append(v)

    def append_qa_instances(self,
                            append_dict,
                            easy_answers=[],
                            hard_answers=[],
                            noisy_answer=[]):
        self.append_relation_and_symbols(append_dict)
        self.easy_answer_list.append(easy_answers)
        self.hard_answer_list.append(hard_answers)
        self.noisy_answer_list.append(noisy_answer)
        self.num_instances

    # TODO  random add sequences
    def append_qa_instances_as_sentence(self, append_dict, answers, random=True):
        for k in answers:
            num_of_answers = len(answers[k])
            break

        # setting the free variable as symbol
        for k in answers:
            if k in self.free_variable_dict:
                self.term_dict[k].state = Term.GROUNDED
                self.clear_var_local_embedding(k)
            else:
                assert k in self.free_variable_dict, "answer for free variables"

        # random ground an answer into the instance
        if random:
            for k in answers:
                answer_sample = sample(answers[k], 1)
                append_dict[k] = answer_sample
            self.append_relation_and_symbols(append_dict)

        else:
            for i in range(num_of_answers):
                for k in answers:
                    answer_sample = answers[k][i]
                    append_dict[k] = answer_sample
                self.append_relation_and_symbols(append_dict)



    # TODO overall probability
    def evaluate_truth_values(self,
                              tnorm: Tnorm,
                              nbp: NeuralBinaryPredicate,
                              margin,
                              all_candidates):
        """
        Input args:
            tnorm_type: the type of tnorms
        Return args:
        """
        return self._evaluate_truth_values(
            self.formula, tnorm, nbp, margin, all_candidates)

    def _evaluate_truth_values(self,
                               formula: Formula,
                               tnorm: Tnorm,
                               nbp: NeuralBinaryPredicate,
                               margin,
                               all_candidates):
        """
        Input args:
            tnorm_type: the type of tnorms
        Return args:
        """
        if isinstance(formula, Conjunction):
            return tnorm.conjunction(
                self._evaluate_truth_values(
                    formula.formulas[0], tnorm, nbp, margin, all_candidates),
                self._evaluate_truth_values(
                    formula.formulas[1], tnorm, nbp, margin, all_candidates)
            )

        elif isinstance(formula, Disjunction):
            return tnorm.disjunction(
                self._evaluate_truth_values(
                    formula.formulas[0], tnorm, nbp, margin, all_candidates),
                self._evaluate_truth_values(
                    formula.formulas[1], tnorm, nbp, margin, all_candidates)
            )

        elif isinstance(formula, Negation):
            return tnorm.negation(
                self._evaluate_truth_values(
                    formula.formula, tnorm, nbp, margin, all_candidates)
            )

        elif isinstance(formula, BinaryPredicate):
            head_name = formula.head.name
            tail_name = formula.tail.name
            head_emb = get_term_embed_from_formula(nbp, self, head_name, all_candidates)
            tail_emb = get_term_embed_from_formula(nbp, self, tail_name, all_candidates)

            rel_emb = nbp.get_relation_emb(formula.relation_id_list)
            batch_score = nbp.embedding_score(
                head_emb, rel_emb, tail_emb
            )
            batch_truth_value = nbp.score2prob(batch_score, margin)
            return batch_truth_value

    @property
    def free_variable_dict(self):
        return {k: v
                for k, v in self.term_dict.items()
                if v.state == Term.FREE or v.state == Term.GROUNDED}

    @property
    def universal_variable_dict(self):
        return {k: v
                for k, v in self.term_dict.items()
                if v.state == Term.UNIVERSAL}

    @property
    def existential_variable_dict(self):
        return {k: v
                for k, v in self.term_dict.items()
                if v.state == Term.EXISTENTIAL}

    @property
    def symbol_dict(self):
        return {k: v
                for k, v in self.term_dict.items()
                if v.state == Term.SYMBOL}

    @property
    def is_sentence(self):
        """
        Determine the state of the formula
        A formula is sentence when all variables are quantified
        """
        return len({k: v for k, v in self.term_dict.items()
                    if v.state == Term.FREE}) == 0

    @property
    def num_instances(self):
        num_instances = len(self.easy_answer_list)
        assert num_instances == len(self.hard_answer_list)
        for k in self.symbol_dict:
            assert num_instances == len(self.get_term_grounded_entity_id_list(k))

        for k in self.predicate_dict:
            assert num_instances == len(self.get_pred_grounded_relation_id_list(k))

        return len(self.easy_answer_list)

    def has_var_local_embedding(self, key):
        return self.term_local_embedding_dict[key] is not None

    def get_var_local_embedding(self, key):
        return self.term_local_embedding_dict[key]

    def set_var_local_embedding(self, key, value):
        self.term_local_embedding_dict[key] = value.detach_()
        self.term_local_embedding_dict[key].requires_grad = True

    def clear_var_local_embedding(self, key):
        self.term_local_embedding_dict[key] = None

    def has_term_grounded_entity_id_list(self, key):
        return len(self.term_grounded_entity_id_dict[key]) > 0

    def get_term_grounded_entity_id_list(self, key):
        return self.term_grounded_entity_id_dict[key]

    def set_term_grounded_entity_id_list(self, key, value):
        self.term_grounded_entity_id_dict[key] = value

    def append_term_grounded_entity_id_list(self, key, value):
        self.term_grounded_entity_id_dict[key].append(value)

    def get_pred_grounded_relation_id_list(self, key):
        return self.pred_grounded_relation_id_dict[key]

    def lstr(self):
        return self.formula.lstr()

    def term_initialized(self, term_name):
        return (self.has_var_local_embedding(term_name) or
                self.has_term_grounded_entity_id_list(term_name))
