"""
A base class for existential first order formulas
It supports the verification and query answering tasks given the formula
For the verification, there is no free_vars
For the query answering, there should be at least one free_vars
Several assumptions about the formula
- In DNF
- Only with existential quantifier
The query is generated by the following steps:

>>>> Construct the conjunctive query skeleton:
    1. Define the number of terms, including
        - p existential vars
        - q free vars
        - r literals
        There are p + q + r terms
    2. Construct the edges between terms by random sampling, and then construct
        a connective graph, the edge is constructed by the certain ratio $P_e$
    3. Randomly corrupt the edges with negation $P_n$
<<<< In this way, the conjunctive query skeleton is constructed

>>>> Construct the DNF formula
    The key of DNF construction is that there must be at least one variable be
    shared in two conjunctive query
    1. determin the variables to be shared (more than one)
    2. determin the objects to be shared (not necessary more than one)
<<<<

>>>> Sampling accross the graph
    1. For question answering task
        1. sample the full graph,
            so that the predicates and objects are determined
        2. search over partial graph and full graph,
            and find out the answer tuples
    2. Instantiation of the query graph
<<<<
"""

from abc import abstractmethod
from collections import defaultdict
import json
from typing import Dict, List

import torch

def check_ldict(ldict):
    """
    Ldict is a nested dict that stores the GROUNDED information
    """
    assert 'op' in ldict
    op = ldict['op']
    assert 'args' in ldict
    args = ldict['args']

    if op == Term.op:
        assert 'name' in args
        assert 'state' in args
        assert 'entity_id_list' in args
    if op == BinaryPredicate.op:
        assert 'name' in args
        assert 'relation_id_list' in args
        check_ldict(args['term1'])
        check_ldict(args['term2'])
    if op == Negation.op:
        assert 'formula' in args
        check_ldict(args['formula'])
    if op == Conjunction.op or op == Disjunction.op:
        assert 'formulas' in args
        for f in args['formulas']:
            check_ldict(f)


def get_ldict(op, **args):
    ans = {'op': op, 'args': args}
    check_ldict(ans)
    return ans


class Lobject:
    @abstractmethod
    def to_ldict(self) -> Dict:
        pass

    @abstractmethod
    def to_lstr(self) -> str:
        pass

    def __repr__(self):
        check_ldict(self.to_ldict())
        return json.dumps(self.to_ldict(), indent=1)

    @abstractmethod
    def get_terms(self) -> Dict[str, 'Term']:
        pass

    @abstractmethod
    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        pass

class Term(Lobject):
    EXISTENTIAL = 1
    FREE = 2
    UNIVERSAL = 3
    SYMBOL = 4

    op = "term"

    def __init__(self, state, name):
        self.state = state
        self.name = name
        self.entity_id_list = []

        self.batch_embedding = None
        self.batch_proposal_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        name = args['name']
        state = args['state']
        object =  cls(name=name, state=state)
        object.entity_id_list = args['entity_id_list']
        return object

    def to_ldict(self):
        ldict = {'op': self.op,
                 'args': {
                   'state': self.state,
                   'name': self.name,
                   'entity_id_list': self.entity_id_list
                   }
              }
        return ldict

    def to_lstr(self) -> str:
        return self.name

    def get_terms(self) -> Dict[str, 'Term']:
        return {self.name: self}

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        return dict()

    def append_proposals(self, proposal):
        batch_size, embedding_dim = proposal.shape
        self.batch_proposal_list.append(
            proposal.view(batch_size, embedding_dim, 1))

    def update_embeddingby_proposals(self):
        batch_proposal_tensor = torch.cat(self.batch_proposal_list, dim=-1)
        self.batch_embedding = torch.mean(batch_proposal_tensor, dim=-1)
        self.batch_proposal_list = []

    # TODO

    # TODO


class Formula(Lobject):
    def __init__(self) -> None:
        super().__init__()

    @staticmethod
    def parse(ldict):
        op = ldict['op']
        if op == BinaryPredicate.op:
            return BinaryPredicate.parse(ldict)
        elif op == Negation.op:
            return Negation.parse(ldict)
        elif op == Conjunction.op:
            return Conjunction.parse(ldict)
        elif op == Disjunction.op:
            return Disjunction.parse(ldict)
        else:
            raise NotImplementedError("Unsupported Operator")


class BinaryPredicate(Formula):
    op = 'pred'

    def __init__(self,
                 name: str,
                 term1: Term,
                 term2: Term) -> None:
        self.name = name
        self.term1 = term1
        self.term2 = term2
        self.relation_id_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']

        name = args['name']
        term1 = Term.parse(args['term1'])
        term2 = Term.parse(args['term2'])
        object = cls(name=name, term1=term1, term2=term2)
        object.relation_id_list = args['relation_id_list']
    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {
                'name': self.name,
                'relation_id_list': self.relation_id_list,
                'term1': self.term1.to_ldict(),
                'term2': self.term2.to_ldict()
            }
        }
        return obj

    def to_lstr(self):
        lstr = f"{self.name}({self.term1.name},{self.term2.name})"
        return lstr

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        ans.update(self.term1.get_terms())
        ans.update(self.term2.get_terms())
        return ans

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {self.name: self}
        return ans


class Negation(Formula):
    op = 'neg'
    def __init__(self, formula: Formula) -> None:
        self.formula = formula

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula = Formula.parse(args['formula'])
        return cls(formula)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formula': self.formula.to_ldict()}
        }
        return obj

    def to_lstr(self) -> str:
        lstr = f"!({self.formula.to_lstr()})"
        return lstr

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        ans.update(self.formula.get_terms())
        return ans

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        ans.update(self.formula.get_predicates())
        return ans

class Conjunction(Formula):
    op = 'conj'
    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict) for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def to_lstr(self):
        lstr = "&".join(f"({f.to_lstr()})" for f in self.formulas)
        return lstr

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_terms())
        return ans

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


class Disjunction(Formula):
    op = 'disj'
    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict) for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def to_lstr(self):
        lstr = "|".join(f"({f.to_lstr()})" for f in self.formulas)
        return lstr

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_terms())
        return ans

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


class FirstOrderFormula:
    """
    The first order formula
    it also includes information about the quantifiers
    """
    def __init__(self, formula: Formula, easy_answer=None, hard_answer=None) -> None:
        self.formula = formula
        self.easy_answer = easy_answer
        self.hard_answer = hard_answer

        # update internal storage
        self.existential_variable_dict = dict()
        self.universal_variable_dict = dict()
        self.free_variable_dict = dict()
        self.symbol_dict = dict()
        terms = self.formula.get_terms()
        for tname, t in terms.items():
            if t.state == Term.EXISTENTIAL:
                self.existential_variable_dict[tname] = t
            if t.state == Term.UNIVERSAL:
                self.universal_variable_dict[tname] = t
            if t.state == Term.FREE:
                self.free_variable_dict[tname] = t
            if t.state == Term.SYMBOL:
                self.symbol_dict[tname] = t

        self.predicate_dict = self.formula.get_predicates()

    def append_relation_and_symbols(self, append_dict):
        for symb_name, symb in self.symbol_dict.items():
            assert symb_name in append_dict
            symb.entity_id_list.append(append_dict[symb_name])

        for pred_name, pred in self.predicate_dict.items():
            assert pred_name in append_dict
            pred.relation_id_list.append(append_dict[pred_name])


    # TODO
    def update_term_dict(self):
        pass

    # TODO implement the initialization
    def initialize_variable_embeddings(self):
        """
        Input args:
        Return args:
            evars: list of existential variables
            uvars: list of universal variables
            fvars: list of free variables
        """
        pass

    # TODO overall probability
    def evaluate_truth_values(self, tnorm_type):
        """
        Input args:
            tnorm_type: the type of tnorms
        Return args:
        """
        pass

    def signature_of_formula():
        pass
