"""
A base class for existential first order formulas
It supports the verification and query answering tasks given the formula
For the verification, there is no free_vars
For the query answering, there should be at least one free_vars
Several assumptions about the formula
- In DNF
- Only with existential quantifier
The query is generated by the following steps:

>>>> Construct the conjunctive query skeleton:
    1. Define the number of terms, including
        - p existential vars
        - q free vars
        - r literals
        There are p + q + r terms
    2. Construct the edges between terms by random sampling, and then construct
        a connective graph, the edge is constructed by the certain ratio $P_e$
    3. Randomly corrupt the edges with negation $P_n$
<<<< In this way, the conjunctive query skeleton is constructed

>>>> Construct the DNF formula
    The key of DNF construction is that there must be at least one variable be
    shared in two conjunctive query
    1. determin the variables to be shared (more than one)
    2. determin the objects to be shared (not necessary more than one)
<<<<

>>>> Sampling accross the graph
    1. For question answering task
        1. sample the full graph,
            so that the predicates and objects are determined
        2. search over partial graph and full graph,
            and find out the answer tuples
    2. Instantiation of the query graph
<<<<
"""

from abc import abstractmethod
import json
from typing import Dict, List

class Lobject:
    @abstractmethod
    @classmethod
    def parse(cls):
        pass

    @abstractmethod
    def to_dict(self) -> Dict:
        pass

    def __repr__(self):
        return json.dumps(self.to_dict())

    @abstractmethod
    def get_terms(self) -> Dict[str, 'Term']:
        pass


class Term(Lobject):
    @classmethod
    def parse(cls, term_obj):
        op = term_obj['op']
        assert op in ['var', 'ltr']
        if op == Variable.op:
            return Variable.parse(term_obj)
        if op == Literal.op:
            return Literal.parse(term_obj)

class Variable(Term):
    EXISTENTIAL = 'E'
    FREE = "F"
    UNIVERSAL = "U"
    op = 'var'

    def __init__(self, name, state) -> None:
        """
        name: the name (identifier) of this variable
        state: the state of this variable
        """
        self.name = name
        assert state in [self.EXISTENTIAL, self.FREE, self.UNIVERSAL]
        self.state = state

    @classmethod
    def parse(cls, term_obj):
        op = term_obj['op']
        assert op == cls.op
        args = term_obj['args']
        return cls(**args)

    def to_dict(self):
        obj = {
            'op': self.op,
            'args': {
                'name': self.name,
                'state': self.state
            }
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        return {self.name, self}


class Literal(Term):
    op = 'lit'

    def __init__(self, name: str, entity_id: int) -> None:
        """
        The id of the entities, -1 for placeholder
        """
        self.name = name
        self.eid = entity_id

    @classmethod
    def parse(cls, term_obj):
        op = term_obj['op']
        assert op == 'ltr'
        args = term_obj['args']
        return cls(**args)

    def to_dict(self):
        obj = {
            'op': self.op,
            'args': {
                'name': self.name,
                'eid': self.eid
            }
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        return {self.name, self}


class Formula(Lobject):
    def __init__(self) -> None:
        super().__init__()

    def parse_formula():
        """Not the same as parse, this is for real logical formula, incase we need it"""
        pass

    @classmethod
    def parse():
        #TODO
        pass


class BinaryPredicate(Formula):
    op = 'pred'

    def __init__(self, relation_id: int, term1: Term, term2: Term) -> None:
        self.relation_id = relation_id
        self.term1 = term1
        self.term2 = term2

    @classmethod
    def parse(cls, atom_obj):
        op = atom_obj['op']
        assert op == cls.op
        args = atom_obj['args']

        pid = args['pid']
        term1 = Term.parse(args['term1'])
        term2 = Term.parse(args['term2'])
        return cls(relation_id=pid, term1=term1, term2=term2)

    def to_dict(self):
        obj = {
            'op': self.op,
            'args': {
                'pid': self.relation_id,
                'term1': self.term1.to_dict(),
                'term2': self.term2.to_dict()
            }
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        ans.update(self.term1.get_terms())
        ans.update(self.term2.get_terms())
        return ans


class Negation(Formula):
    op = 'neg'
    def __init__(self, formula: Formula) -> None:
        self.formula = formula

    @classmethod
    def parse(cls, atom_obj):
        op = atom_obj['op']
        assert op == cls.op
        args = atom_obj['args']
        formula = args['formula']
        return cls(formula)

    def to_dict(self):
        obj = {
            'op': self.op,
            'args': {'pred': self.pred.to_dict()}
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        ans.update(self.formula.get_terms)
        return ans


class Conjunction(Formula):
    op = 'conj'
    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, conj_obj):
        op = conj_obj['op']
        assert op == cls.op
        args = conj_obj['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict) for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_dict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_dict() for f in self.formulas]}
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_terms)
        return ans


class Disjunction(Formula):
    op = 'disj'
    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, disj_obj):
        op = disj_obj['op']
        assert op == cls.op
        args = disj_obj['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict) for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_dict(self):
        obj = {
            'op': 'disj',
            'args': {'formulas': [f.to_dict() for f in self.formulas]}
        }
        return obj

    def get_terms(self) -> Dict[str, 'Term']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_terms)
        return ans

# class DNF(Form):
#     def __init__(self, conjunctions: List[Conjunction]) -> None:
#         self.conjunctions = conjunctions

#     @classmethod
#     def parse(cls, dnf_obj):
#         op = dnf_obj['op']
#         assert op == 'dnf'
#         args = dnf_obj['args']
#         conj_obj_list = args['conjs']
#         conjunctions = [Conjunction.parse(conj_obj)
#                         for conj_obj in conj_obj_list]
#         return cls(conjunctions)

#     def to_dict(self):
#         obj = {
#             'op': 'dnf',
#             'args': {'conjs': [c.to_dict() for c in self.conjunctions]}
#         }


# class DNFFormula:
#     """
#     A base class for the string input of the entire formula structure
#     """

#     def __init__(self,
#                  exist_vars: Dict[str, Variable],
#                  free_vars: Dict[str, Variable],
#                  literals: Dict[str, Variable],
#                  dnf: DNF):
#         self.exist_vars = exist_vars
#         self.free_vars = free_vars
#         self.literals = literals
#         self.dnf = dnf

#     @classmethod
#     def loads(cls, s: str):
#         obj = json.loads(s)

#         evars = obj['EVAR'].split(',')
#         fvars = obj['FVAR'].split(',')
#         ltrs = obj['LTR'].split(',')
#         dnf_obj = obj['DNF']
#         dnf = DNF.parse(dnf_obj)
#         return cls(evars, fvars, ltrs, dnf)

#     def dumps(self):
#         obj = {
#             'EVAR': ','.join([str(k) for k in self.exist_vars]),
#             'FVAR': ','.join([str(k) for k in self.free_vars]),
#             'LTR': ','.join([str(k) for k in self.literals]),
#             'DNF': self.dnf.to_dict()
#         }
#         return json.dumps(obj)
