"""
A base class for existential first order formulas
It supports the verification and query answering tasks given the formula
For the verification, there is no free_vars
For the query answering, there should be at least one free_vars
Several assumptions about the formula
- In DNF
- Only with existential quantifier
The query is generated by the following steps:

>>>> Construct the conjunctive query skeleton:
    1. Define the number of terms, including
        - p existential vars
        - q free vars
        - r literals
        There are p + q + r terms
    2. Construct the edges between terms by random sampling, and then construct
        a connective graph, the edge is constructed by the certain ratio $P_e$
    3. Randomly corrupt the edges with negation $P_n$
<<<< In this way, the conjunctive query skeleton is constructed

>>>> Construct the DNF formula
    The key of DNF construction is that there must be at least one variable be
    shared in two conjunctive query
    1. determin the variables to be shared (more than one)
    2. determin the objects to be shared (not necessary more than one)
<<<<

>>>> Sampling accross the graph
    1. For question answering task
        1. sample the full graph,
            so that the predicates and objects are determined
        2. search over partial graph and full graph,
            and find out the answer tuples
    2. Instantiation of the query graph
<<<<
"""

from abc import abstractmethod
from collections import defaultdict
import json
from typing import Dict, List
from src.language.tnorm import ProductTNorm, Tnorm
from src.structure.neural_binary_predicate import NeuralBinaryPredicate

def check_ldict(ldict):
    """
    Ldict is a nested dict that stores the GROUNDED information
    """
    assert 'op' in ldict
    op = ldict['op']
    assert 'args' in ldict
    args = ldict['args']

    if op == Term.op:
        assert 'name' in args
        assert 'state' in args
        assert 'entity_id_list' in args
    if op == BinaryPredicate.op:
        assert 'name' in args
        assert 'relation_id_list' in args
        check_ldict(args['term1'])
        check_ldict(args['term2'])
    if op == Negation.op:
        assert 'formula' in args
        check_ldict(args['formula'])
    if op == Conjunction.op or op == Disjunction.op:
        assert 'formulas' in args
        for f in args['formulas']:
            check_ldict(f)


def get_ldict(op, **args):
    ans = {'op': op, 'args': args}
    check_ldict(ans)
    return ans


class Lobject:
    op = "default"
    @abstractmethod
    def to_ldict(self) -> Dict:
        pass

    @abstractmethod
    def to_lstr(self) -> str:
        pass

    def __repr__(self):
        check_ldict(self.to_ldict())
        return json.dumps(self.to_ldict(), indent=1)

    @abstractmethod
    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        pass


class Term(Lobject):
    EXISTENTIAL = 1
    FREE = 2
    UNIVERSAL = 3
    SYMBOL = 4

    op = "term"

    def __init__(self, state, name):
        self.state = state
        self.name = name
        self.entity_id_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        name = args['name']
        state = args['state']
        object = cls(name=name, state=state)
        object.entity_id_list = args['entity_id_list']
        return object

    def to_ldict(self):
        ldict = {'op': self.op,
                 'args': {
                     'state': self.state,
                     'name': self.name,
                     'entity_id_list': self.entity_id_list}}
        return ldict

    def to_lstr(self) -> str:
        return self.name

    @property
    def is_free(self):
        return self.state == self.FREE

    @property
    def is_existential(self):
        return self.state == self.EXISTENTIAL

    @property
    def is_universal(self):
        return self.state == self.UNIVERSAL

    @property
    def is_symbol(self):
        return self.state == self.SYMBOL

class Formula(Lobject):
    def __init__(self) -> None:
        super().__init__()

    @staticmethod
    def parse(ldict):
        op = ldict['op']
        if op == BinaryPredicate.op:
            return BinaryPredicate.parse(ldict)
        elif op == Negation.op:
            return Negation.parse(ldict)
        elif op == Conjunction.op:
            return Conjunction.parse(ldict)
        elif op == Disjunction.op:
            return Disjunction.parse(ldict)
        else:
            raise NotImplementedError("Unsupported Operator")


class BinaryPredicate(Formula):
    op = 'pred'

    def __init__(self,
                 name: str,
                 term1: Term,
                 term2: Term) -> None:
        self.name = name
        self.term1 = term1
        self.term2 = term2
        self.relation_id_list = []

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']

        name = args['name']
        term1 = Term.parse(args['term1'])
        term2 = Term.parse(args['term2'])
        object = cls(name=name, term1=term1, term2=term2)
        object.relation_id_list = args['relation_id_list']

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {
                'name': self.name,
                'relation_id_list': self.relation_id_list,
                'term1': self.term1.to_ldict(),
                'term2': self.term2.to_ldict()
            }
        }
        return obj

    def to_lstr(self):
        lstr = f"{self.name}({self.term1.name},{self.term2.name})"
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {self.name: self}
        return ans

    def get_terms(self):
        return [self.term1, self.term2]

class Connective(Formula):
    pass

class Negation(Connective):
    op = 'neg'

    def __init__(self, formula: Formula) -> None:
        self.formula = formula

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula = Formula.parse(args['formula'])
        return cls(formula)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formula': self.formula.to_ldict()}
        }
        return obj

    def to_lstr(self) -> str:
        lstr = f"!({self.formula.to_lstr()})"
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        ans.update(self.formula.get_predicates())
        return ans


class Conjunction(Connective):
    op = 'conj'

    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict)
                    for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def to_lstr(self):
        lstr = "&".join(f"({f.to_lstr()})" for f in self.formulas)
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


class Disjunction(Connective):
    op = 'disj'

    def __init__(self, formulas: List[Formula]) -> None:
        self.formulas = formulas

    @classmethod
    def parse(cls, ldict):
        op = ldict['op']
        assert op == cls.op
        args = ldict['args']
        formula_dict_list = args['formulas']
        formulas = [Formula.parse(formula_dict)
                    for formula_dict in formula_dict_list]
        return cls(formulas)

    def to_ldict(self):
        obj = {
            'op': self.op,
            'args': {'formulas': [f.to_ldict() for f in self.formulas]}
        }
        return obj

    def to_lstr(self):
        lstr = "|".join(f"({f.to_lstr()})" for f in self.formulas)
        return lstr

    def get_predicates(self) -> Dict[str, 'BinaryPredicate']:
        ans = {}
        for f in self.formulas:
            ans.update(f.get_predicates())
        return ans


class FirstOrderFormula:
    """
    The first order formula
    it also includes information about the quantifiers

    self.formula is parsed from the formula and provide the operator tree for
        evaluation
    self.predicate_dict stores each predicates by its name, which are edges
    self.symbol_dict stores each symbol by its name
    self.variable_dict stores each variable by its name

    self.easy_answer_list list for easy answers
    self.hard_answer_list list for hard answers
    self.noisy_answer_list list for noisy answers

    each answer is a dict whose keys are the variable and values are the list of possible answers

    """
    existential_variable_dict: Dict[str, Term]
    universal_variable_dict: Dict[str, Term]
    free_variable_dict: Dict[str, Term]
    symbol_dict: Dict[str, Term]

    def __init__(self,
                 formula: Formula) -> None:

        self.formula: Formula = formula
        self.easy_answer_list = []
        self.hard_answer_list = []
        self.noisy_answer_list = []
        # update internal storage
        self.predicate_dict = self.formula.get_predicates()
        self.symbol_dict = {}
        self.variable_dict: Dict[str, Term] = {}
        for _, pred in self.predicate_dict.items():
            for t in pred.get_terms():
                if t.state == Term.SYMBOL:
                    self.symbol_dict[t.name] = t
                else:
                    self.variable_dict[t.name] = t
        self.variable_local_embedding_dict = {k: None for k in self.variable_dict}

    def append_relation_and_symbols(self, append_dict):
        for symb_name, symb in self.symbol_dict.items():
            assert symb_name in append_dict
            symb.entity_id_list.append(append_dict[symb_name])

        for pred_name, pred in self.predicate_dict.items():
            assert pred_name in append_dict
            pred.relation_id_list.append(append_dict[pred_name])

    def append_qa_instances(self,
                            append_dict,
                            easy_answers=[],
                            hard_answers=[],
                            noisy_answer=[]):
        self.append_relation_and_symbols(append_dict)
        self.easy_answer_list.append(easy_answers)
        self.hard_answer_list.append(hard_answers)
        self.noisy_answer_list.append(noisy_answer)

    def append_qa_instances_as_sentence(self, append_dict, answers):
        for k in answers:
            num_of_answers = len(answers[k])
            break

        # setting the free variable as symbol
        for k in answers:
            if k in self.variable_dict:
                self.symbol_dict[k] = self.variable_dict.pop(k)
                self.symbol_dict[k].state = Term.SYMBOL
            else:
                assert k in self.symbol_dict
                assert k not in self.free_variable_dict

        for i in range(num_of_answers):
            for k in answers:
                append_dict[k] = answers[k][i]

            self.append_relation_and_symbols(append_dict)


    # TODO overall probability
    def evaluate_truth_values(self, tnorm: Tnorm, nbp: NeuralBinaryPredicate, margin):

        """
        Input args:
            tnorm_type: the type of tnorms
        Return args:
        """
        return self._evaluate_truth_values(self.formula, tnorm, nbp, margin)

    def _evaluate_truth_values(self, formula, tnorm, nbp: NeuralBinaryPredicate, margin):
        """
        Input args:
            tnorm_type: the type of tnorms
        Return args:
        """
        if formula.op == Conjunction.op:
            return tnorm.conjunction(
                self._evaluate_truth_values(formula.formulas[0], tnorm, nbp, margin),
                self._evaluate_truth_values(formula.formulas[1], tnorm, nbp, margin)
            )

        elif formula.op == Disjunction.op:
            return tnorm.disjunction(
                self._evaluate_truth_values(formula.formulas[0], tnorm, nbp, margin),
                self._evaluate_truth_values(formula.formulas[1], tnorm, nbp, margin)
            )

        elif formula.op == Negation.op:
            return tnorm.negation(
                self._evaluate_truth_values(formula.formula, tnorm, nbp, margin)
            )

        elif formula.op == BinaryPredicate.op:
            head_term = formula.term1
            if head_term.is_symbol:
                head_emb = nbp.get_entity_emb(head_term.entity_id_list)
            else:
                head_emb = self.get_var_local_embedding(head_term.name)

            tail_term = formula.term2
            if tail_term.is_symbol:
                tail_emb = nbp.get_entity_emb(tail_term.entity_id_list)
            else:
                tail_emb = self.get_var_local_embedding(tail_term.name)

            rel_emb = nbp.get_relation_emb(formula.relation_id_list)
            batch_score = nbp.embedding_score(
                head_emb, rel_emb, tail_emb
            )
            batch_truth_value = nbp.score2prob(batch_score, margin)
            return batch_truth_value


    @property
    def free_variable_dict(self):
        return {k: v
                for k, v in self.variable_dict.items()
                if v.state == Term.FREE}

    @property
    def universal_variable_dict(self):
        return {k: v
                for k, v in self.variable_dict.items()
                if v.state == Term.UNIVERSAL}

    @property
    def existential_variable_dict(self):
        return {k: v
                for k, v in self.variable_dict.items()
                if v.state == Term.EXISTENTIAL}

    @property
    def is_sentence(self):
        """
        Determine the state of the formula
        A formula is sentence when all variables are quantified
        """
        return len(self.free_variable_dict) == 0

    @property
    def num_instances(self):
        return len(self.easy_answer)

    def get_var_local_embedding(self, key):
        return self.variable_local_embedding_dict[key]

    def has_var_local_embedding(self, key):
        return self.variable_local_embedding_dict[key] is not None

    def set_var_local_embedding(self, key, value):
        self.variable_local_embedding_dict[key] = value.detach_()
        self.variable_local_embedding_dict[key].requires_grad = True

    def to_lstr(self):
        return self.formula.to_lstr()
